### ISSUE TITLE
polymerfire#0.10.1 introduces `firebase.app().database` is not a function.

### ISSUE THREAD

**Issue by jifalops** [firebase/polymerfire#180]
### Description

I am using `<firebase-app app="{{app}}" ...` to start using firebase when the app has been loaded. An example usage is to get a reference via `var ref = firebase.app().database().ref('/users');` works fine in 0.9.4 through 0.10.0, but fails in 0.10.1 with the exception `Uncaught TypeError: firebase.app(...).database is not a function`.

**Edit:** Using polymer 1.8.0 and firebase 3.6.8.

### Expected outcome
I am able to use `firebase.app().database().ref('/users');` as soon as `app` in `<firebase-app app="{{app}}" ...` returns an object.

### Actual outcome
`<firebase-app app="{{app}}" ...` returns an object, but then `var ref = firebase.app().database().ref('/users');` causes an exception that `database` is not a function.

### Browsers Affected

- [ x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by tjmonsi** [comment]
I think this is very much the same with #179

**Comment by jifalops** [comment]
@tjmonsi you are correct. Importing the script fixed the issue.

```
<link rel="import" href="../bower_components/polymerfire/firebase-database-script.html">
```
